# This workflow generates the code coverage report and uploads it to Codecov.

name: Generate Code Coverage
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install python
      uses: actions/setup-python@master
      with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install yfrake
        pip install pytest
        pip install pytest-asyncio
        pip install coverage

    - name: Generate coverage report
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload report to codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
