name: YFrake Main Workflow
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install python
      uses: actions/setup-python@master
      with:
        python-version: 3.10.2

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install poetry
      uses: abatilo/actions-poetry@v2.1.3

    - name: Process poetry
      run: |
        poetry install
#        poetry run gen_spec
#        poetry build

#    - name: Publish to PyPI
#      uses: JRubics/poetry-publish@v1.10
#      with:
#        pypi_token: ${{ secrets.PYPI_TOKEN }}
#
#    - name: Generate coverage report
#      run: |
#        coverage run -m pytest
#        coverage xml
    
    - name: run tests
      run: pytest --cov-report xml --cov=yfrake tests/

    - name: Upload report to codecov
      uses: codecov/codecov-action@v2
      with:
        env_vars: OS,PYTHON
#        directory: ./coverage/reports/
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true

