name: Example workflow for Codecov
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

#    - name: Update pip
#      run: python -m pip install --upgrade pip

    - name: Install poetry
      uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.1.13

    - name: Poetry processing
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry install
        poetry run gen_spec
        poetry build
        poetry publish
#    - name: Install dependencies
#      run: |
#
#        pip install pytest
#        pip install pytest-asyncio
#        pip install coverage
#    - name: Install poetry
#
#    - name: Run image
#      uses: abatilo/actions-poetry@v2.0.0
#      run: |
#        poetry update
#
#
#    - name: Generate coverage report
#      run: |
#
#        coverage run -m pytest
#        coverage xml
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v2
#      with:
#        directory: ./coverage/reports/
#        env_vars: OS,PYTHON
#        fail_ci_if_error: true
#        files: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        path_to_write_report: ./coverage/codecov_report.txt
#        verbose: true
#    - name: Run image
#      uses: abatilo/actions-poetry@v2.0.0