name: Example workflow for Codecov
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  # checkout repository
    - uses: actions/setup-python@master  # install python
      with:
        python-version: 3.7
      run: python -m pip install --upgrade pip  # upgrade pip
    - uses: Gr1N/setup-poetry@v7  # install poetry
      with:
        poetry-version: 1.1.13
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # get publishing token
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry install
        poetry run gen_spec
        poetry build
        poetry publish
#    - name: Install dependencies
#      run: |
#
#        pip install pytest
#        pip install pytest-asyncio
#        pip install coverage
#    - name: Install poetry
#
#    - name: Run image
#      uses: abatilo/actions-poetry@v2.0.0
#      run: |
#        poetry update
#
#
#    - name: Generate coverage report
#      run: |
#
#        coverage run -m pytest
#        coverage xml
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v2
#      with:
#        directory: ./coverage/reports/
#        env_vars: OS,PYTHON
#        fail_ci_if_error: true
#        files: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        path_to_write_report: ./coverage/codecov_report.txt
#        verbose: true
#    - name: Run image
#      uses: abatilo/actions-poetry@v2.0.0